import "%modules%/header/header";
import "%modules%/footer/footer";
import "%modules%/video/video";
import "%modules%/galleryThumbs/galleryThumbs";
import "%modules%/comments/comments";
import "%modules%/likeItem/likeItem";
import "%modules%/information-systems-search/information-systems-search";
import "%modules%/spoiler/spoiler";
import "%modules%/select/select";
import '%modules%/dataselect/dataselect';
import '%modules%/unknown/unknown';
import '%modules%/universal-form/universal-form'
import '%modules%/imagePopup/imagePopup'